### ISSUE TITLE
Collect ideas for the content people would like to see in the "Resources" section

### ISSUE THREAD

**Issue by jag1g13** [socrse/trustees#6]
This issue is an ongoing one, for people to provide suggestions and feedback for content under the "Resources" section of the SocRSE website (not yet created, as of time of writing).

**Comment by jag1g13** [comment]
- Links to existing training materials for RSEs to deliver
  - e.g. Software Carpentry and bespoke training developed by RSEs
- Case studies on the structure of established RSE groups

**Comment by milliams** [comment]
All of my training material is online at https://milliams.com/courses and I think would fit the brief.

**Comment by aturner-epcc** [comment]
- Definitions of RSE skills (James Smithies KCL report)
   - RSE job descriptions

**Comment by mwoodbri** [comment]
Two of our training courses, inspired by https://github-pages.ucl.ac.uk/rsd-engineeringcourse/:
* https://github.com/ImperialCollegeLondon/grad_school_git_course/
* https://github.com/ImperialCollegeLondon/grad_school_software_engineering_course/

**Comment by jag1g13** [comment]
@aniabrown Has created a resources collection on our website that can be used to suggest resources of interest to the community

See https://society-rse.org/resources/
